name: Build Fyne App

on:
  push:
    branches:
      - main  # Or replace 'main' with your default branch name

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build macOS app
        run: make darwin

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-macos
          path: nopass

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Windows app
        run: make win

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-windows
          path: nopass.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install lib
        run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
      - name: Build Linux app
        run: make linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-linux
          path: nopass