name: Build Fyne App

on:
  push:
    branches:
      - main  # Or replace 'main' with your default branch name

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fyne CLI
        run: go get -u fyne.io/fyne/v2/cmd/fyne

      - name: Build macOS app
        run: fyne package -os darwin -name nopass

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-macos
          path: nopass.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Fyne CLI
        run: go get -u fyne.io/fyne/v2/cmd/fyne

      - name: Build Windows app
        run: fyne package -os windows -name nopass

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-windows
          path: nopass.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fyne CLI
        run: go get -u fyne.io/fyne/v2/cmd/fyne

      - name: Build Linux app
        run: fyne package -os linux -name nopass

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: fyne-app-linux
          path: nopass